METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12
  
  lr: 0.001
  batch_size: 64
  max_epochs: 200

  load_adj: False
  pass_device: False

  model_args:
    num_nodes: 207
    out_steps: 12
    input_dim: 2
    output_dim: 1
    embed_dim: 8
    rnn_units: 64
    num_layers: 2
    cheb_k: 2
    default_graph: True
