METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12
  
  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 30]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: False

  load_npz: False
  with_embeddings: False
  
  pass_device: False

  model_args:
    num_nodes: 207
    out_steps: 12
    input_dim: 1
    output_dim: 1
    embed_dim: 8
    rnn_units: 64
    num_layers: 2
    cheb_k: 2
    default_graph: True

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12
  
  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 30]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: False

  load_npz: False
  with_embeddings: False
  
  pass_device: False

  model_args:
    num_nodes: 325
    out_steps: 12
    input_dim: 1
    output_dim: 1
    embed_dim: 8
    rnn_units: 64
    num_layers: 2
    cheb_k: 2
    default_graph: True
