METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12
  
  lr: 0.001
  batch_size: 64
  max_epochs: 200

  load_npz: True
  load_adj: False
  pass_device: True

  model_args:
    num_nodes: 207
    in_dim: 2
    out_dim: 12
    # adj_path: "../data/METRLA/adj_mx.pkl"
    adj_path: null
    adj_type: "doubletransition"
    device: null # will be updated
    