METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [80]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  load_npz: True
  pass_device: True

  model_args:
    num_nodes: 207
    in_dim: 2
    out_dim: 12
    adj_path: "../data/METRLA/adj_mx.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [50]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: True
  cl_step_size: 2500

  load_npz: True
  pass_device: True

  model_args:
    num_nodes: 325
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMSBAY/adj_mx_bay.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null
    