METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  batch_size: 64
  max_epochs: 200

  load_adj: True
  adj_path: "../data/METRLA/W_metrla.csv"
  pass_device: True

  model_args:
    num_nodes: 207
    in_steps: 12
    adj: null # will be updated
    device: null # will be updated
    ks: 3
    kt: 3
    bs: [[1, 16, 64], [64, 16, 64]]
    p: 0
  