METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12
  
  lr: 0.001
  weight_decay: 0
  milestones: [10, 40]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: False

  load_npz: False
  with_embeddings: True
  
  adj_path: null
  pass_device: False

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    lstm_input_dim: 1
    lstm_hidden_dim: 64
    st_embedding_dim: 96
    learner_hidden_dim: 64
    z_dim: 32
    towards: True
  