METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12
  
  lr: 0.01
  weight_decay: 0.0001
  milestones: [5, 20]
  clip_grad: False
  batch_size: 64
  max_epochs: 200
  use_cl: False

  load_npz: False
  with_embeddings: True
  
  adj_path: null
  pass_device: False

  model_args:
    num_nodes: 207
    out_steps: 12
    lstm_input_dim: 1
    lstm_hidden_dim: 64
    t_embedding_dim: 32
    learner_hidden_dim: 64
  