METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  milestones: [10, 35]
  batch_size: 64
  max_epochs: 200
  use_cl: False
  load_npz: True
  pass_device: False

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    model_dim: 64
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.001
  milestones: [10, 35]
  batch_size: 64
  max_epochs: 200
  use_cl: False
  load_npz: True
  pass_device: False

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    model_dim: 64
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
