ELECTRICITY:
  num_nodes: 207
  in_steps: 336
  out_steps: 96

  lr: 0.001
  weight_decay: 0.0001
  milestones: [30, 50]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  runner: ltsf
  loss: mse

  model_args:
    seq_len: 336
    pred_len: 96
    individual: False
    enc_in: 207
