METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  time_of_day: True

  runner: GTS
  loss: GTS

  lr: 0.005
  eps: 0.001
  milestones: [20, 30, 40]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 207
    input_dim: 2
    output_dim: 1
    seq_len: 12
    horizon: 12
    rnn_units: 64
    num_rnn_layers: 1
    max_diffusion_step: 3
    filter_type: "dual_random_walk"
    tf_decay_steps: 2000
    use_teacher_forcing: True
    l1_decay: 0
    temp: 0.5
    k: 10
    dim_fc: 383552
    dataset_name: "METRLA"
    trainset_ratio: 0.7

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  time_of_day: True

  runner: GTS
  loss: GTS

  lr: 0.005
  eps: 0.001
  milestones: [20, 30, 40]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 325
    input_dim: 2
    output_dim: 1
    seq_len: 12
    horizon: 12
    rnn_units: 64
    num_rnn_layers: 1
    max_diffusion_step: 3
    filter_type: "dual_random_walk"
    tf_decay_steps: 2000
    use_teacher_forcing: True
    l1_decay: 0
    temp: 0.5
    k: 30
    dim_fc: 583408
    dataset_name: "PEMSBAY"
    trainset_ratio: 0.7

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  time_of_day: True

  runner: GTS
  loss: GTS

  lr: 0.001
  eps: 0.001
  milestones: [20, 30]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 358
    input_dim: 2
    output_dim: 1
    seq_len: 12
    horizon: 12
    rnn_units: 64
    num_rnn_layers: 1
    max_diffusion_step: 3
    filter_type: "dual_random_walk"
    tf_decay_steps: 2000
    use_teacher_forcing: True
    l1_decay: 0
    temp: 0.5
    k: 30
    dim_fc: 251312
    dataset_name: "PEMS03"
    trainset_ratio: 0.6

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  time_of_day: True

  runner: GTS
  loss: GTS

  lr: 0.001
  eps: 0.001
  milestones: [20, 30]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 307
    input_dim: 2
    output_dim: 1
    seq_len: 12
    horizon: 12
    rnn_units: 64
    num_rnn_layers: 1
    max_diffusion_step: 3
    filter_type: "dual_random_walk"
    tf_decay_steps: 2000
    use_teacher_forcing: True
    l1_decay: 0
    temp: 0.5
    k: 30
    dim_fc: 162832
    dataset_name: "PEMS04"
    trainset_ratio: 0.6

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  time_of_day: True

  runner: GTS
  loss: GTS

  lr: 0.001
  eps: 0.001
  milestones: [20, 30]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 883
    input_dim: 2
    output_dim: 1
    seq_len: 12
    horizon: 12
    rnn_units: 64
    num_rnn_layers: 1
    max_diffusion_step: 3
    filter_type: "dual_random_walk"
    tf_decay_steps: 2000
    use_teacher_forcing: True
    l1_decay: 0
    temp: 0.5
    k: 30
    dim_fc: 270656
    dataset_name: "PEMS07"
    trainset_ratio: 0.6

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  time_of_day: True

  runner: GTS
  loss: GTS

  lr: 0.001
  eps: 0.001
  milestones: [20, 30]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 170
    input_dim: 2
    output_dim: 1
    seq_len: 12
    horizon: 12
    rnn_units: 64
    num_rnn_layers: 1
    max_diffusion_step: 3
    filter_type: "dual_random_walk"
    tf_decay_steps: 2000
    use_teacher_forcing: True
    l1_decay: 0
    temp: 0.5
    k: 30
    dim_fc: 171136
    dataset_name: "PEMS08"
    trainset_ratio: 0.6
