METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  # milestones: [80]
  milestones: [40]
  clip_grad: False
  batch_size: 64
  max_epochs: 200

  pass_device: True

  model_args:
    num_nodes: 207
    in_dim: 2
    out_dim: 12
    adj_path: "../data/METRLA/adj_mx.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  # milestones: [50]
  milestones: [40]
  clip_grad: False
  batch_size: 64
  max_epochs: 200

  pass_device: True

  model_args:
    num_nodes: 325
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMSBAY/adj_mx_bay.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  # milestones: [115]
  milestones: [40]
  clip_grad: False
  batch_size: 64
  max_epochs: 200

  pass_device: True

  model_args:
    num_nodes: 358
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS03/adj_PEMS03_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  # milestones: [175]
  milestones: [40]
  early_stop: 15
  clip_grad: False
  batch_size: 64
  max_epochs: 500

  pass_device: True

  model_args:
    num_nodes: 307
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS04/adj_PEMS04_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  # milestones: [108]
  milestones: [40]
  clip_grad: False
  batch_size: 64
  max_epochs: 200

  pass_device: True

  model_args:
    num_nodes: 883
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS07/adj_PEMS07_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  time_of_day: True
  
  lr: 0.001
  weight_decay: 0.0001
  # milestones: [168]
  milestones: [40]
  early_stop: 15
  clip_grad: False
  batch_size: 64
  max_epochs: 300

  pass_device: True

  model_args:
    num_nodes: 170
    in_dim: 2
    out_dim: 12
    adj_path: "../data/PEMS08/adj_PEMS08_distance.pkl"
    adj_type: "doubletransition"
    device: null # will be updated
    dropout: 0.3
    gcn_bool: True
    addaptadj: True
    aptinit: null
    