METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 20]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 207
    seq_len: 12
    pred_len: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
    num_layers: 3

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 20]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 325
    seq_len: 12
    pred_len: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
    num_layers: 3

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 20]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 358
    seq_len: 12
    pred_len: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
    num_layers: 3

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 20]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 307
    seq_len: 12
    pred_len: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
    num_layers: 3

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0.0001
  milestones: [20, 30]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 883
    seq_len: 12
    pred_len: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
    num_layers: 3

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0.0001
  milestones: [10, 20]
  clip_grad: 5
  batch_size: 64
  max_epochs: 200
  early_stop: 10

  model_args:
    num_nodes: 170
    seq_len: 12
    pred_len: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
    num_layers: 3
