METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 300
  use_cl: False

  model_args:
    in_steps: 12
    out_steps: 12
    input_dim: 1
    output_dim: 1
    hidden_dim: 256
