ELECTRICITY:
  num_nodes: 321
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [30, 50]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 32
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 321
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2 
    fc_dropout: 0.2 
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

WEATHER:
  num_nodes: 21
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 21
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2 
    fc_dropout: 0.2 
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

TRAFFIC:
  num_nodes: 862
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 862
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2 
    fc_dropout: 0.2 
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

EXCHANGE:
  num_nodes: 8
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 8
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2 
    fc_dropout: 0.2 
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

ETTH1:
  num_nodes: 7
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 7
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.3
    fc_dropout: 0.3
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

ETTH2:
  num_nodes: 7
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 7
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.3
    fc_dropout: 0.3
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

ETTM1:
  num_nodes: 7
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 7
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2 
    fc_dropout: 0.2 
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25

ETTM2:
  num_nodes: 7
  in_steps: 336
  out_steps: 96

  lr: 0.0001
  weight_decay: 0
  milestones: [10]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    enc_in: 7
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2 
    fc_dropout: 0.2 
    head_dropout: 0
    patch_len: 16 
    stride: 8 
    individual: 0
    padding_patch: "end"
    revin: 1 
    affine: 0 
    subtract_last: 0 
    decomposition: 0 
    kernel_size: 25
