METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 200

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0001
  milestones: [10, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0005
  milestones: [15, 30, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300

  model_args:
    num_nodes: 307
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.001
  milestones: [15, 35, 50]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300

  model_args:
    num_nodes: 883
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0015
  milestones: [25, 45, 65]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300

  model_args:
    num_nodes: 170
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

# This is abandoned, needs further tuning if you want to run
PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0005
  milestones: [15, 30, 40]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 300

  model_args:
    num_nodes: 358
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    spatial_embedding_dim: 0
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMSD7M:
  num_nodes: 228
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 200
  
  model_args:
    num_nodes: 228
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    days_per_week: 5
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

PEMSD7L:
  num_nodes: 1026
  in_steps: 12
  out_steps: 12

  time_of_day: True
  day_of_week: True

  lr: 0.001
  weight_decay: 0.0003
  milestones: [20, 30]
  lr_decay_rate: 0.1
  batch_size: 16
  max_epochs: 200
  
  model_args:
    num_nodes: 1026
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    days_per_week: 5
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
    dropout: 0.1

ELECTRICITY:
  num_nodes: 321
  in_steps: 96
  out_steps: 96 # 96 192 336 720

  time_of_day: True
  day_of_week: True

  lr: 0.0001
  weight_decay: 0
  milestones: [10, 30]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 16
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    num_nodes: 321
    in_steps: 96
    out_steps: 96
    steps_per_day: 24
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 1
    dropout: 0.1

ETTH1:
  num_nodes: 7
  in_steps: 96
  out_steps: 96

  time_of_day: True
  day_of_week: True

  lr: 0.0001
  weight_decay: 0
  milestones: [10, 30]
  lr_decay_rate: 0.1
  clip_grad: 0
  batch_size: 16
  max_epochs: 200

  dataloader: ltsf
  runner: ltsf
  loss: mse

  model_args:
    num_nodes: 7
    in_steps: 96
    out_steps: 96
    steps_per_day: 24
    input_dim: 3
    output_dim: 1
    input_embedding_dim: 24
    tod_embedding_dim: 24
    dow_embedding_dim: 24
    adaptive_embedding_dim: 80
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 1
    dropout: 0.1
