METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  milestones: [10, 60]
  batch_size: 8
  max_epochs: 200
  use_cl: False

  model_args:
    num_nodes: 207
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 72
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  milestones: [10, 40]
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    num_nodes: 325
    in_steps: 12
    out_steps: 12
    steps_per_day: 288
    input_dim: 1
    output_dim: 1
    input_embedding_dim: 12
    tod_embedding_dim: 12
    dow_embedding_dim: 12
    adaptive_embedding_dim: 72
    feed_forward_dim: 256
    num_heads: 4
    num_layers: 3
