METRLA:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 207
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMSBAY:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 325
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMS03:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 358
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMS04:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 307
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMS07:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 883
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMS08:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 170
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMSD7M:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 228
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True

PEMSD7L:
  in_steps: 12
  out_steps: 12

  lr: 0.001
  milestones: []
  clip_grad: False
  batch_size: 16
  max_epochs: 200
  early_stop: 15

  pass_device: True

  model_args:
    num_nodes: 1026
    input_dim: 1
    output_dim: 1
    lag: 12
    horizon: 12
    device: null # will be updated
    channels: 16
    memory_size: 16
    dynamic: True
