METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2

PEMSBAY:
  num_nodes: 325
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2

PEMS03:
  num_nodes: 358
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2

PEMS04:
  num_nodes: 307
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2

PEMS07:
  num_nodes: 883
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2

PEMS08:
  num_nodes: 170
  in_steps: 12
  out_steps: 12

  lr: 0.01
  weight_decay: 0
  milestones: [10, 30]
  clip_grad: 0
  batch_size: 64
  max_epochs: 300

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2
