METRLA:
  num_nodes: 207
  in_steps: 12
  out_steps: 12

  train_size: 0.7
  val_size: 0.1
  
  lr: 0.01
  weight_decay: 0
  milestones: [10, 20]
  clip_grad: 0
  batch_size: 64
  max_epochs: 200
  use_cl: False

  model_args:
    in_channels: 1
    out_channels: 12
    hidden_channels: 16
    kernel_size: 2
    num_blocks: 4
    num_layers: 2
    